// <auto-generated />
namespace SEPAMIAR_SGC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_clientes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_clientes));
        
        string IMigrationMetadata.Id
        {
            get { return "201608280516129_alter_clientes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
