// <auto-generated />
namespace SEPAMIAR_SGC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AACC_100916_1749 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AACC_100916_1749));
        
        string IMigrationMetadata.Id
        {
            get { return "201609102251542_AACC_100916_1749"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
